const TIERS = ["Bronze", "Argent", "Or", "Platine", "Diamant"];
const DEFAULT_REWARDS = [20, 40, 70, 110, 160];

const ACHIEVEMENTS = [
  // STREAK GLOBAL — 5 succès racines
  {
    id: "streak_global_1",
    category: "streak_global",
    name: "Habitude naissante",
    description: "Commence à construire ton rythme.",
    metric: "streakGlobal",
    unit: "jours",
    thresholds: [3, 5, 7, 10, 14],
    tiers: TIERS,
    rewardXp: DEFAULT_REWARDS,
  },
  {
    id: "streak_global_2",
    category: "streak_global",
    name: "Rythme solide",
    description: "Tu tiens la cadence sur la durée.",
    metric: "streakGlobal",
    unit: "jours",
    thresholds: [15, 20, 25, 28, 30],
    tiers: TIERS,
    rewardXp: DEFAULT_REWARDS,
  },
  {
    id: "streak_global_3",
    category: "streak_global",
    name: "Discipline continue",
    description: "La régularité devient une seconde nature.",
    metric: "streakGlobal",
    unit: "jours",
    thresholds: [40, 50, 60, 75, 90],
    tiers: TIERS,
    rewardXp: DEFAULT_REWARDS,
  },
  {
    id: "streak_global_4",
    category: "streak_global",
    name: "Machine de régularité",
    description: "Ton rythme est inébranlable.",
    metric: "streakGlobal",
    unit: "jours",
    thresholds: [100, 120, 150, 180, 200],
    tiers: TIERS,
    rewardXp: DEFAULT_REWARDS,
  },
  {
    id: "streak_global_5",
    category: "streak_global",
    name: "Légende vivante",
    description: "Une constance digne d’une légende.",
    metric: "streakGlobal",
    unit: "jours",
    thresholds: [250, 300, 365, 400, 500],
    tiers: TIERS,
    rewardXp: DEFAULT_REWARDS,
  },

  // STREAK PAR CHALLENGE
  {
    id: "streak_pushups",
    category: "streak_challenge",
    name: "Pompes régulières",
    description: "Enchaîne les séances de pompes sans casser la chaîne.",
    metric: "streak:pushups",
    unit: "jours",
    thresholds: [3, 7, 14, 30, 60],
    tiers: TIERS,
    rewardXp: DEFAULT_REWARDS,
  },
  {
    id: "streak_plank",
    category: "streak_challenge",
    name: "Gainage régulier",
    description: "Garde le rythme sur le gainage jour après jour.",
    metric: "streak:plank",
    unit: "jours",
    thresholds: [3, 7, 14, 30, 60],
    tiers: TIERS,
    rewardXp: DEFAULT_REWARDS,
  },
  {
    id: "streak_abs",
    category: "streak_challenge",
    name: "Abdos réguliers",
    description: "Enchaîne les séances d'abdos sans relâcher l'effort.",
    metric: "streak:abs",
    unit: "jours",
    thresholds: [3, 7, 14, 30, 60],
    tiers: TIERS,
    rewardXp: DEFAULT_REWARDS,
  },
  {
    id: "streak_triceps",
    category: "streak_challenge",
    name: "Triceps réguliers",
    description: "Reste constant sur le challenge triceps.",
    metric: "streak:triceps",
    unit: "jours",
    thresholds: [3, 7, 14, 30, 60],
    tiers: TIERS,
    rewardXp: DEFAULT_REWARDS,
  },
  {
    id: "streak_bench",
    category: "streak_challenge",
    name: "Développé régulier",
    description: "Accumule les jours sur le challenge développé.",
    metric: "streak:bench",
    unit: "jours",
    thresholds: [3, 7, 14, 30, 60],
    tiers: TIERS,
    rewardXp: DEFAULT_REWARDS,
  },

  // VOLUME
  {
    id: "volume_pushups",
    category: "volume",
    name: "Pompes cumulées",
    description: "Accumule un gros volume sur les pompes.",
    metric: "totalPompes",
    unit: "pompes",
    thresholds: [100, 500, 2000, 8000, 20000],
    tiers: TIERS,
    rewardXp: DEFAULT_REWARDS,
  },
  {
    id: "volume_plank",
    category: "volume",
    name: "Gainage cumulé",
    description: "Accumule du temps total en gainage.",
    metric: "stats.totalGainage",
    unit: "secondes",
    thresholds: [300, 1000, 4000, 12000, 30000],
    tiers: TIERS,
    rewardXp: DEFAULT_REWARDS,
  },
  {
    id: "volume_abs",
    category: "volume",
    name: "Abdos cumulés",
    description: "Accumule un gros volume sur les abdos.",
    metric: "stats.totalAbdos",
    unit: "répétitions",
    thresholds: [100, 500, 2000, 8000, 20000],
    tiers: TIERS,
    rewardXp: DEFAULT_REWARDS,
  },
  {
    id: "volume_triceps",
    category: "volume",
    name: "Triceps cumulés",
    description: "Accumule un gros volume sur les triceps.",
    metric: "stats.totalTriceps",
    unit: "répétitions",
    thresholds: [100, 500, 2000, 8000, 20000],
    tiers: TIERS,
    rewardXp: DEFAULT_REWARDS,
  },
  {
    id: "volume_bench",
    category: "volume",
    name: "Développé cumulé",
    description: "Accumule un gros volume sur le développé.",
    metric: "stats.totalDeveloppe",
    unit: "répétitions",
    thresholds: [100, 500, 2000, 8000, 20000],
    tiers: TIERS,
    rewardXp: DEFAULT_REWARDS,
  },

  // XP TOTAL
  {
    id: "xp_total",
    category: "xp",
    name: "Accumulation",
    description: "Empile les XP au fil des séances.",
    metric: "xpTotal",
    unit: "XP",
    thresholds: [200, 500, 1500, 5000, 15000],
    tiers: TIERS,
    rewardXp: DEFAULT_REWARDS,
  },

  // LIGUES
  {
    id: "league_1",
    category: "leagues",
    name: "Atteindre ligue 1",
    description: "Commence ton parcours en ligue 1.",
    metric: "league.bestLeague",
    unit: "ligue",
    thresholds: [1],
    tiers: ["Bronze"],
    rewardXp: [20],
  },
  {
    id: "league_2",
    category: "leagues",
    name: "Atteindre ligue 2",
    description: "Passe un cap et monte en ligue 2.",
    metric: "league.bestLeague",
    unit: "ligue",
    thresholds: [2],
    tiers: ["Bronze"],
    rewardXp: [20],
  },
  {
    id: "league_3",
    category: "leagues",
    name: "Atteindre ligue 3",
    description: "Continue la progression en ligue 3.",
    metric: "league.bestLeague",
    unit: "ligue",
    thresholds: [3],
    tiers: ["Bronze"],
    rewardXp: [20],
  },
  {
    id: "league_4",
    category: "leagues",
    name: "Atteindre ligue 4",
    description: "Atteins la ligue 4 et consolide ton niveau.",
    metric: "league.bestLeague",
    unit: "ligue",
    thresholds: [4],
    tiers: ["Bronze"],
    rewardXp: [20],
  },
  {
    id: "league_5",
    category: "leagues",
    name: "Atteindre ligue 5",
    description: "Passe la moitié du tableau en ligue 5.",
    metric: "league.bestLeague",
    unit: "ligue",
    thresholds: [5],
    tiers: ["Bronze"],
    rewardXp: [20],
  },
  {
    id: "league_6",
    category: "leagues",
    name: "Atteindre ligue 6",
    description: "Une ligue exigeante mais à ta portée.",
    metric: "league.bestLeague",
    unit: "ligue",
    thresholds: [6],
    tiers: ["Bronze"],
    rewardXp: [20],
  },
  {
    id: "league_7",
    category: "leagues",
    name: "Atteindre ligue 7",
    description: "Un rythme solide en ligue 7.",
    metric: "league.bestLeague",
    unit: "ligue",
    thresholds: [7],
    tiers: ["Bronze"],
    rewardXp: [20],
  },
  {
    id: "league_8",
    category: "leagues",
    name: "Atteindre ligue 8",
    description: "Tu rivalises avec les meilleurs en ligue 8.",
    metric: "league.bestLeague",
    unit: "ligue",
    thresholds: [8],
    tiers: ["Bronze"],
    rewardXp: [20],
  },
  {
    id: "league_9",
    category: "leagues",
    name: "Atteindre ligue 9",
    description: "Le top approche avec la ligue 9.",
    metric: "league.bestLeague",
    unit: "ligue",
    thresholds: [9],
    tiers: ["Bronze"],
    rewardXp: [20],
  },
  {
    id: "league_10",
    category: "leagues",
    name: "Atteindre ligue 10",
    description: "La ligue 10, sommet absolu.",
    metric: "league.bestLeague",
    unit: "ligue",
    thresholds: [10],
    tiers: ["Bronze"],
    rewardXp: [20],
  },

  // FUN
  {
    id: "fun_sessions",
    category: "fun",
    name: "Toujours partant",
    description: "Multiplie les séances pour garder le fun.",
    metric: "totalSessions",
    unit: "séances",
    thresholds: [5, 20, 50, 100, 200],
    tiers: TIERS,
    rewardXp: DEFAULT_REWARDS,
  },

  // SÉANCES COMBINÉES
  {
    id: "combined_sessions",
    category: "combined",
    name: "Enchaînement",
    description: "Enchaîne plusieurs challenges dans une même séance.",
    metric: "combinedSessions",
    unit: "séances",
    thresholds: [10, 50, 200, 300, 500],
    tiers: TIERS,
    rewardXp: DEFAULT_REWARDS,
  },
];

window.ACHIEVEMENTS = ACHIEVEMENTS;
